version: '3.7'

services:
  api:
    image: scans-api
    build: ./api
    env_file: ./api/.env
    volumes:
      - api_npm_cache:/root/.npm
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  dashboard:
    image: scans-dashboard
    build: ./dashboard
    env_file: ./dashboard/.env
    ports:
      - 3000:3000
    volumes:
      - dashboard_npm_cache:/root/.npm
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  api_npm_cache:
  dashboard_npm_cache:
