version: '3.7'

services:
  api:
    image: scans-api
    build: ./api
    volumes:
      - npm_cache:/root/.npm
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  dashboard:
    image: scans-dashboard
    build: ./dashboard
    volumes:
      - npm_cache:/root/.npm
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  npm_cache:
