#!/usr/bin/env node

require('dotenv').config();

const MongoDatabase = require('../../../infrastructure/persistence/mongodb/MongoDatabase');
const CreateScans = require('../../../actions/CreateScans');
const ScansRepository = require('../../../infrastructure/persistence/mongodb/scans/ScansMongoRepository');

const mongo = new MongoDatabase();
const scansRepository = new ScansRepository();
const createScans = new CreateScans({ scansRepository });

const { number } = require('yargs')
  .usage('Usage: $0 --number [num]')
  .demandOption(['number'])
  .argv;

mongo.start()
  .then(() => createScans.execute({ number }))
  .then(() => mongo.close())
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });